apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-server-role
  namespace: argo
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflows/finalizers", "workflowtemplates", "workflowtemplates/finalizers", "cronworkflows", "cronworkflows/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-server-rb
  namespace: argo
subjects:
- kind: ServiceAccount
  name: default 
  namespace: default  
roleRef:
  kind: Role
  name: argo-server-role
  apiGroup: rbac.authorization.k8s.io
