apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
  namespace: argo
rules:
- apiGroups:
    - argoproj.io
  resources:
    - workflows
    - workflowtemplates
    - cronworkflows
    - workflowtaskresults
    - workflowtasksets
  verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-role-binding
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo
