apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials
  namespace: gdi
type: Opaque
data:
  username: a2V5Y2xvYWsK 
  password: YVdOTFNVNUVTVk50U1U1bgo= 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pg-pv
  namespace: gdi
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/keycloak-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: gdi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: keycloak-pg-pv
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-svc
  namespace: gdi
  labels:
    app: keycloak-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    app: keycloak-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-postgres-sts
  namespace: gdi
  labels:
    app: keycloak-postgres
spec:
  serviceName: keycloak-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
        - name: keycloak-postgres-pod
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "keycloak"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-credentials
                  key: username 
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-credentials
                  key: password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc

