apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows-admin
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-admin-binding
subjects:
  - kind: Group
    name: "admin" 
roleRef:
  kind: Role
  name: argo-workflows-admin
  apiGroup: rbac.authorization.k8s.io
