apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  sso: |
    issuer: http://keycloak:8080/realms/argo
    clientId:
      name: argo-sso-secret
      key: client-id
    clientSecret:
      name: argo-sso-secret
      key: client-secret
    redirectUrl: https://localhost:2746/oauth2/callback/
    scopes: 
     - groups
    rbac:
      enabled: true

